### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by Hendrix-Shen** [sakura-ryoko/malilib#13]
In #5, parameter changes in ConfigDouble[^1] constructor may break the compatibility of existing mod. Should the missing constructor be re-added. Btw, ConfigInteger[^2] worked as expected.

[^1]: https://github.com/sakura-ryoko/malilib/pull/5/commits/0d911cedae0c07018da20bf60c7ec3cfe97c1e94#diff-c0bdcf30f1d299e40d4350c00dbc6d9347313888fe56dfca3abf293a3bd48fd7L28-L31
[^2]: https://github.com/sakura-ryoko/malilib/pull/5/commits/0d911cedae0c07018da20bf60c7ec3cfe97c1e94#diff-6fe210e21acc551ca438009abd9d215bf6e5004f98925250cc9a0fe420289ad9L28-R45

**Comment by sakura-ryoko** [comment]
Hello Hendrix!  Welcome to my git hub, you are always welcome to make PR's as well!

**Comment by sakura-ryoko** [comment]
Also See this: https://github.com/sakura-ryoko/malilib/commit/8aeeb403073bf85777853a15e5dc2e838fbef6df

I'm not going to do a release just yet, but you can still use the commit for Jitpack

**Comment by sakura-ryoko** [comment]
sakura.8 fixes this issue
