### ISSUE TITLE
malilib 1.21.3 (0.22.0/sakura.7) doesnt work with lunar client

### ISSUE THREAD

**Issue by ForbiddenTexts** [sakura-ryoko/malilib#24]
[crash-2024-11-20_02.24.23-client.txt](https://github.com/user-attachments/files/17826818/crash-2024-11-20_02.24.23-client.txt)

crashes upon initialization, when using Lunar client 1.21.3

**Comment by sakura-ryoko** [comment]
In my experience these problems are usually a lunar client problem; and from the error log they are rejecting a "Normal" mixin injection into the world; because Lunar Client is hacking things into the World Rendering where they probably shouldn't for a Client.

**Comment by sakura-ryoko** [comment]
Also, the way I crafted these Mixins was to do minimal (Next to nothing) changes to Vanilla for the MaLiLib world rendering hooks by adding MaLiLib's own "World RenderPass" phases.  This is very brittle code in the sense of things breaking if any changes whatsoever are made, and will not be changed.

Lunar broke it, so it's their job to fix it.  Not mine.  Launchers should not be making such changes to the Vanilla game.

**Comment by ForbiddenTexts** [comment]
Thanks for the explanation
