### ISSUE TITLE
Translation of Malilib into Ukrainian

### ISSUE THREAD

**Issue by StarmanMine142** [sakura-ryoko/malilib#31]
Could you add the Ukrainian translation created by me?

[uk_ua.json](https://github.com/user-attachments/files/18054168/uk_ua.json)

**Comment by sakura-ryoko** [comment]
Sure thing, I'll add it!

**Comment by sakura-ryoko** [comment]
Added, thank you.  The entries all check out.

**Comment by StarmanMine142** [comment]
I added a translation for the lines that were added recently.

[uk_ua.json](https://github.com/user-attachments/files/18058544/uk_ua.json)

And noticed a possible error in line 197, at the beginning there is "ile", but maybe it should have been "File"

**Comment by StarmanMine142** [comment]
I added a translation for the lines that were added recently

[uk_ua.json](https://github.com/user-attachments/files/18083179/uk_ua.json)

**Comment by sakura-ryoko** [comment]
Merged from PR

**Comment by StarmanMine142** [comment]
Hello again! Сorrections and improvements

[uk_ua.json](https://github.com/user-attachments/files/18103016/uk_ua.json)
